apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: fordt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: acrfordtdevci.azurecr.io/fordt/backend:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
