apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: fordt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: acrfordtdevci.azurecr.io/fordt/frontend:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: "http://backend.fordt.svc.cluster.local:8080"
